### ISSUE TITLE
Support for building images w/ CuPy - requires cuda drivers 

### ISSUE THREAD

**Issue by phlp-cg** [NVIDIA/gpu-operator#45]
We are currently running Openshift 4 in AWS and we have enabled the gpu operators in our cluster on p3.2xlarge instances. 

We successfully installed the gpu operator by following the blog post below, and  verified the nvidia pods are up and running. 

https://blog.openshift.com/simplifying-deployments-of-accelerated-ai-workloads-on-red-hat-openshift-with-nvidia-gpu-operator/

oc get pods
NAME                                       READY   STATUS      RESTARTS   AGE
nvidia-container-toolkit-daemonset-tdrf9   1/1     Running     0          2d22h
nvidia-device-plugin-daemonset-f4hbb       1/1     Running     0          2d22h
nvidia-device-plugin-validation            0/1     Completed   0          29m
nvidia-driver-daemonset-8xgzf              1/1     Running     0          2d22h
nvidia-driver-validation                   0/1     Completed   0          2d22h
 
We are attempting to perform an container image build, which includes installing CuPy (https://docs-cupy.chainer.org/en/stable/install.html#run-cupy-with-docker) in our image.
For our container image build, we are scheduling the build on the gpu worker node (p3.2xlarge) , which has the nvidia drivers installed from the gpu operators. 

I’m not sure if the gpu operator we installed contains all the dependencies required for these type of builds.  Was wondering if the nvidia team can help determine that. 

Here are the error messages when we try to install CuPy in our container images.    
Error Message
Downloading cupy-7.2.0.tar.gz (3.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d0ofpwo0/cupy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d0ofpwo0/cupy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-d0ofpwo0/cupy/pip-egg-info
         cwd: /tmp/pip-install-d0ofpwo0/cupy/
    Complete output (47 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}
    
    -------- Configuring Module: cuda --------
    /tmp/tmpzyaacm2s/a.cpp:1:23: fatal error: cublas_v2.h: No such file or directory
     #include <cublas_v2.h>
                           ^
    compilation terminated.
    command 'gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: []
      Library directories: []
      nvcc command       : (not found)
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
      ROCM_HOME       : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.

**Comment by rmccorm4** [comment]
Hi @phlp-cg ,

In general I believe the GPU Operator is just meant for mounting the nvidia driver into your containers.

Your container images will still need to have the CUDA runtime/toolkit and the proper environment variables (PATH/LD_LIBRARY_PATH) setup correctly in order to use CUDA applications, just like on a regular machine.

> We are attempting to perform an container image build, which includes installing CuPy in our image.

Can you share some more details on the image/Dockerfile that you're trying to install CuPy in?

I believe one simple/easy way to make sure the image has everything necessary to run CUDA applications is to inherit your image from our NGC CUDA images in your Dockerfile. 

For example,
```
# Dockerfile
FROM nvcr.io/nvidia/cuda:10.0-devel-ubuntu18.04

# Install dependencies
# ...

# Install cupy
# ...
```

Please note that I believe only the CUDA images with the tag `*-devel-*` will come with everything you need pre-configured for running CUDA apps.

**Comment by phlp-cg** [comment]
Thanks for the info! We were able to proceed with the build by downloading the CUDA & toolkits in our base image.
